---
- name: Ensure SSH Directories
  become: yes
  file:
    path: /home/vagrant/.ssh
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0700

# - name: Copy SSH Key Files
#   become: yes
#   copy:
#     src: files/{{ item }}
#     dest: /home/vagrant/.ssh/{{ item }}
#     owner: vagrant
#     group: vagrant
#     mode: 0600
#   with_items:
#     - config

- name: Remove Default Host Entry
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1\s+k8s.*$'
    state: absent

- name: Ensure Hosts File
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: "{{ item.ip }} {{ item.name }}"
  with_items:
    - { ip: "172.42.42.11", name: "k8s1" }
    - { ip: "172.42.42.12", name: "k8s2" }
    - { ip: "172.42.42.13", name: "k8s3" }

# - name: Ensure Google Cloud Apt Key
#   become: yes
#   apt_key:
#     url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
#     state: present
#   tags:
#     - k8s

# - name: Ensure Kubernetes Repository
#   become: yes
#   apt_repository:
#     repo: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
#     state: present
#     update_cache: yes
#   tags:
#     - k8s

# - name: Ensure Base Kubernetes
#   become: yes
#   apt:
#     pkg:
#       - apt-transport-https
#       - docker-engine
#       - kubelet
#       - kubeadm
#       - kubectl
#       - kubernetes-cni
#       - jq
#     state: latest
#   tags:
#     - k8s

- name: Ensure Docker Group
  group:
    name: docker
    state: present

- name: Ensure User in Docker Group
  user:
    name=vagrant
    groups=docker
    append=yes

- name: Ensure Kubernetes Cleanup
  become:
  copy:
    src: files/clean-k8s
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root
